/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.prism.ui.contentassist

import org.cmg.ml.sam.xtext.prism.ui.contentassist.AbstractPrismProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PrismProposalProvider extends AbstractPrismProposalProvider {
}
