/*
* generated by Xtext
*/
package org.cmg.ml.sam.xtext.prism.ui.contentassist;

import org.cmg.ml.sam.xtext.prism.ui.contentassist.AbstractPrismProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PrismProposalProvider extends AbstractPrismProposalProvider {

}
