/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.lprm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LprSpecificationUiModule extends org.cmg.ml.sam.xtext.lprm.ui.AbstractLprSpecificationUiModule {
	public LprSpecificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
