/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.prism.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.cmg.ml.sam.xtext.prism.services.PrismGrammarAccess;

public class PrismParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PrismGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.cmg.ml.sam.xtext.prism.parser.antlr.internal.InternalPrismParser createParser(XtextTokenStream stream) {
		return new org.cmg.ml.sam.xtext.prism.parser.antlr.internal.InternalPrismParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PrismGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PrismGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
