/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.prism.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PrismAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/cmg/ml/sam/xtext/prism/parser/antlr/internal/InternalPrism.tokens");
	}
}
