/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.prism.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPrismValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.cmg.ml.sam.xtext.prism.prism.PrismPackage.eINSTANCE);
		return result;
	}
}
