/*
* generated by Xtext
*/
package org.cmg.ml.sam.xtext.population.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PopulationOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
