/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.lprm.ui.contentassist

import org.cmg.ml.sam.xtext.lprm.ui.contentassist.AbstractLprSpecificationProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LprSpecificationProposalProvider extends AbstractLprSpecificationProposalProvider {
}
