/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.klaim.ui.contentassist

import org.cmg.ml.sam.xtext.klaim.ui.contentassist.AbstractKlaimProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class KlaimProposalProvider extends AbstractKlaimProposalProvider {
}
