/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.klaim.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KlaimUiModule extends org.cmg.ml.sam.xtext.klaim.ui.AbstractKlaimUiModule {
	public KlaimUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
