/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.population.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PopulationUiModule extends org.cmg.ml.sam.xtext.population.ui.AbstractPopulationUiModule {
	public PopulationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return org.cmg.ml.sam.xtext.population.ui.wizard.CustomPopulationProjectCreator.class;
	}
	
	
}
