/*
* generated by Xtext
*/
package org.cmg.ml.sam.xtext.population.ui.contentassist;

import org.cmg.ml.sam.xtext.population.ui.contentassist.AbstractPopulationProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PopulationProposalProvider extends AbstractPopulationProposalProvider {

}
