/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.klaim;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KlaimRuntimeModule extends org.cmg.ml.sam.xtext.klaim.AbstractKlaimRuntimeModule {

}
