/*
* generated by Xtext
*/
package org.cmg.ml.sam.xtext.klaim;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class KlaimStandaloneSetup extends KlaimStandaloneSetupGenerated{

	public static void doSetup() {
		new KlaimStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

