/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.prism.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PrismUiModule extends org.cmg.ml.sam.xtext.prism.ui.AbstractPrismUiModule {
	public PrismUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
