/*
* generated by Xtext
*/
package org.cmg.ml.sam.xtext.lprm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LprSpecificationStandaloneSetup extends LprSpecificationStandaloneSetupGenerated{

	public static void doSetup() {
		new LprSpecificationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

