/*
 * generated by Xtext
 */
package org.cmg.ml.sam.xtext.lprm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LprSpecificationRuntimeModule extends org.cmg.ml.sam.xtext.lprm.AbstractLprSpecificationRuntimeModule {

}
